CREATE TABLE IF NOT EXISTS rate_limit_buckets (
  bucket_key   VARCHAR(190) NOT NULL PRIMARY KEY,
  window_start INT UNSIGNED NOT NULL,
  count        INT UNSIGNED NOT NULL DEFAULT 0,
  updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_rlb_window (window_start)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
