CREATE TABLE IF NOT EXISTS flussi_rendicontazioni (
  id                  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  id_dominio          VARCHAR(20) NOT NULL,
  id_flusso           VARCHAR(100) NOT NULL,
  data_flusso         DATE,
  data_regolamento    DATE,
  trn                 VARCHAR(50),
  id_psp              VARCHAR(50),
  ragione_psp         VARCHAR(255),
  anno                SMALLINT UNSIGNED NOT NULL,
  mese                TINYINT UNSIGNED NOT NULL,
  iur                 VARCHAR(35) NOT NULL,
  iuv                 VARCHAR(35),
  importo             DECIMAL(10,2),
  esito               TINYINT,
  stato_rend          VARCHAR(20),
  indice              SMALLINT,
  data_pagamento      DATE,
  cod_entrata         VARCHAR(100),
  descrizione_entrata VARCHAR(500),
  id_pendenza         VARCHAR(100),
  synced_at           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_iur_dominio (iur, id_dominio),
  INDEX idx_dominio_flusso (id_dominio, id_flusso),
  INDEX idx_dominio_data (id_dominio, data_pagamento),
  INDEX idx_dominio_anno_mese (id_dominio, anno, mese),
  INDEX idx_dominio_entrata (id_dominio, cod_entrata)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
