CREATE TABLE IF NOT EXISTS biz_ricevute (
  id                   BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  id_dominio           VARCHAR(20)     NOT NULL,
  id_flusso            VARCHAR(100),
  iur                  VARCHAR(35)     NOT NULL,
  iuv                  VARCHAR(35),
  anno                 YEAR            NOT NULL,
  mese                 TINYINT UNSIGNED NOT NULL,
  data_pagamento       DATE,
  importo              DECIMAL(10,2),
  descrizione          VARCHAR(512),
  cf_debitore          VARCHAR(35),
  nominativo_debitore  VARCHAR(255),
  cf_pagante           VARCHAR(35),
  nominativo_pagante   VARCHAR(255),
  company_name         VARCHAR(255),
  trasferimenti        JSON,
  stato                ENUM('PENDING','PROCESSED','ERROR','SKIPPED') NOT NULL DEFAULT 'PENDING',
  error_msg            TEXT,
  created_at           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_iur_dominio (iur, id_dominio),
  INDEX idx_stato_id (stato, id),
  INDEX idx_dominio_anno_mese (id_dominio, anno, mese)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
